turobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_front_hinge_effort_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}
#  left_rear_hinge_controller:
#    type: effort_controllers/JointPositionController
#    joint: left_rear_hinge
#    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_front_hinge_effort_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}
#  right_rear_hinge_controller:
#    type: effort_controllers/JointPositionController
#    joint: right_rear_hinge
#    pid: {p: 100.0, i: 0.01, d: 10.0}
